### ISSUE TITLE
Illegal option -o pipefail

### ISSUE THREAD

**Issue by papermache** [alexzhangs/aws-ec2-shadowsocks-libev#1]
sudo sh aws-ec2-shadowsocks-libev/install.sh
aws-ec2-shadowsocks-libev/install.sh: 4: set: Illegal option -o pipefail

**Comment by alexzhangs** [comment]
Could you give the version of Shell that was used for the installation?
```
sudo sh --version
```

**Comment by alexzhangs** [comment]
use the following command to invoke the installer:

```
bash aws-ec2-shadowsocks-libev/install.sh
```
